### ISSUE TITLE
[plugin] afelio-building-blocks

### ISSUE THREAD

**Issue by MGinettiPro** [gilsdav/ng-afelio#108]
La repo URL n'est pas valide.

$ ng-afelio plugin afelio -l

C:\[...]\AppData\Roaming\nvm\v18.17.1\node_modules\ng-afelio\node_modules\node-fetch\lib\index.js:273
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at http://[git]/afelio-building-blocks/repository/tags reason: Unexpected token < in JSON at position 0
    at C:\[...]\AppData\Roaming\nvm\v18.17.1\node_modules\ng-afelio\node_modules\node-fetch\lib\index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GitlabConnector.getCompatiblePlugins (C:\[...]\AppData\Roaming\nvm\v18.17.1\node_modules\ng-afelio\schematics\plugin\connectors\connector.js:10:24) {    
  type: 'invalid-json'
}

**Comment by gilsdav** [comment]
c'est pas quand ton token n'est pas valide ça ?

**Comment by MGinettiPro** [comment]
On a essayer avec un token identique sur ma machine et celle de Boris et lui n'avait pas le soucis
